# Push時はCIのみ、Merge時はCIおよびCDを実行するGitHub Actionsを作る（単一のWorkflowで）
# https://dev.classmethod.jp/articles/create-github-actions-that-run-ci-only-when-push-and-ci-and-cd-when-merging-in-a-single-workflow/

on:
  push:

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Print Node.js version 🔍
        run: node --version

      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: Copy env file 📝
        run: cp .env.dist .env.local

      - name: Cache Next.js Dependency 🏷
        uses: actions/cache@v3
        id: cache_nextjs_dependency_id
        env:
          cache-name: cache-nextjs-dependency
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}

      - name: Install Next.js Dependency 📦
        if: ${{ steps.cache_nextjs_dependency_id.outputs.cache-hit != 'true' }}
        run: rm -rf node_modules && yarn install --frozen-lockfile

      - name: Build Test 🛠
        run: |
          yarn build
          yarn sitemap

      - name: Install jq 📦
        run: yarn add global jq

      # クライアントIDとS3バケット名を環境変数から読み込んでJSONに設定する
      - name: Set reg-suit config 📝
        run: |
          cat regconfig.json | jq '.plugins."reg-notify-github-plugin".clientId|="${{ secrets.REG_SUIT_CLIENT_ID }}"' > regconfig.json
          cat regconfig.json | jq '.plugins."reg-publish-s3-plugin".bucketName|="${{ secrets.REG_SUIT_S3_BUCKET_NAME }}"' > regconfig.json

      - name: Visual Regression Test 🖼
        run: |
          yarn storycap
          yarn regression -v

  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main' }}
    needs: integration
    steps:
      - name: Print Node.js version 🔍
        run: node --version

      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: Copy env file 📝
        run: cp .env.dist .env.local

      - name: Cache Next.js Dependency 🏷
        uses: actions/cache@v3
        id: cache_nextjs_dependency_id
        env:
          cache-name: cache-nextjs-dependency
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}

      - name: Generate Next.js 🧑🏻‍💻
        run: yarn export

      - name: Deploy to Firebase 🔥
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_YURIKAGO_BLOG }}'
          channelId: live
          projectId: yurikago-blog
